version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/code
    steps:
      - checkout
      # 修改这里，添加参数以自动接受变更
      - run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y upx
      - restore_cache:
          key: go-pkg-{{ checksum "go.sum" }}
      - run: ./build-release.sh
      - save_cache:
          paths:
            - /go/pkg
          key: go-pkg-{{ checksum "go.sum" }}
      - store_artifacts:
          path: bin
          destination: bin